### ISSUE TITLE
Better support async request when sending emails

### ISSUE THREAD

**Issue by CXRunfree** [resendlabs/resend-python#122]

**Comment by IvanObreshkov** [comment]
@CXRunfree From what I have looked at, this won't be an easy task as they are using the std `requests` library, which is not `async`. They will probably need to write a whole new implementation using an async requests library like [httpx](https://www.python-httpx.org/).

If you are using FastAPI you could use [BackgroundTasks.add_task()](https://fastapi.tiangolo.com/tutorial/background-tasks/) to send the emails asynchronously.

If you are using something else but still need `async` sending of emails you could write a wrapper yourself using  [to_thread](https://docs.python.org/3/library/asyncio-task.html#asyncio.to_thread).

If, for some reason, you need to have a cancelation mechanism due to some time constraints or not wanting to wait indefinitely for the result from `resend`, you can provide a timeout via [wait_for](https://docs.python.org/3/library/asyncio-task.html#asyncio.wait_for). Keep in mind that `wait_for` will cancel the future returned (not the thread), but unfortunately, the thread will continue running indefinitely, which could create strange behavior. You can check more [here](https://github.com/python/cpython/issues/87185). Instead, you should be using [asyncio.loop.run_in_executor](https://docs.python.org/3.10/library/asyncio-eventloop.html#asyncio.loop.run_in_executor) to schedule the background task and get a future you can use `wait_for` to wait on the event-loop.

**Comment by drish** [comment]
thanks a lot for the explanation @IvanObreshkov !, we will create a native asyncio version of the SDK sometime in the future, for now I have created an example repo on how to wrap your code around `to_thread`: https://github.com/resend/resend-examples/tree/main/with-python-asyncio. I will make this example available in the README and docs too.
