### ISSUE TITLE
Implement Separate Event Handling for Emails

### ISSUE THREAD

**Issue by brenonsc** [resendlabs/resend-python#68]
Currently, when multiple recipients are included in an email list, all events triggered by any recipient's actions are shared via webhooks. This causes an issue where any action taken by one recipient triggers webhook updates for all recipients, regardless of their involvement. To enhance the functionality and provide better control over event handling, it would be beneficial to implement separate event handling for each recipient's actions.

### Proposed Solution:
Introduce a mechanism to differentiate between events triggered by individual recipients within the email list. This could involve assigning unique identifiers or tags to each recipient's actions, allowing webhooks to selectively process events based on their origin.

**Comment by drish** [comment]
thanks for your suggestion @brenonsc 🙏 , I will share it with the team and will let you know here

**Comment by zenorocha** [comment]
Thanks for the feedback @brenonsc. Are you using multiple `to`'s? If yes, a workaround for this would be using a single `to`, that way the webhook would be triggered only to that recipient.

Since this is not specific to Python SDK, I'll be closing this issue, but your suggestion is still valid, so we'll add it to our feature request board.
